name: CI Workflow with Groups

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  group1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  group2:
    runs-on: ubuntu-latest
    needs: group1  # Ensure this runs after group1 job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Group 2 - Run linting
        run: |
          echo "Running linting for group 2"
          # Command for linting

      - name: Group 2 - Deploy
        run: |
          echo "Deploying for group 2"
          # Command for deploying

  group3:
    runs-on: ubuntu-latest
    needs: group1  # Ensure this runs after group1 job
    if: github.event_name == 'push'  # Run only on push events
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Group 3 - Run security scan
        run: |
          echo "Running security scan for group 3"
          # Command for security scanning

      - name: Group 3 - Build documentation
        run: |
          echo "Building documentation for group 3"
          # Command for building documentation
